name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
  predeploy:    
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - name: Pre deploy
        run: npm predeploy  
  deploy:    
    runs-on: ubuntu-latest
    needs: [predeploy]

    steps:
      - uses: actions/checkout@v2
      - name: Pre deploy
        run: gh-pages -d build       
