name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gh-pages
      run: npm install gh-pages --save-dev
      
  build:    
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm build  
        
  deploy:    
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          git remote set-url origin https://git:${{ secrets.SEC_TOKEN }}@github.com/react-project.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}     
