name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gh-pages
      run: npm install -g gh-pages
  build:    
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm build  
  deploy:    
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: gh-pages -d build       
